<a href="https://colab.research.google.com/github/ulvem/Time-to-Practice-Numpy-25-30/blob/main/Copy_of_Time_to_Practice_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img height="180px" src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" align="left" hspace="30px" vspace="50px"/>

# Welcome to your next notebook with SDA!

During the classes we will mostly use [Google Colaboratory](https://colab.research.google.com/?hl=en) which is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

However, for bigger projects, especially involving Deep Learning and/or big data reading, it might be a better choice to setup Jupyter Notebook or Jupyter Lab on your computer. Also, it is worth noticing that there is a great number of useful extensions (see [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) and [jupyter-labextension](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html)) not available for Colab users.

<img src="https://drive.google.com/uc?export=view&id=1UO2urRciECzoKE_vHy4RMGfFbkOWOGlW" alt="SDA logo" align="left" width="100px" hspace="10px" vspace="10px"/>
<br>

# TASKS

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Linear Algebra

### Please make sure that **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.1 - 1.10</font>** and **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.10 - 1.24</font>** are already completed :)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.25</font>**

For the matrix from task 1.7:
* calculate its determinant,
* find inverse matrix.

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

Next, change the last value to 0:
$$
B=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 0
\end{bmatrix}
$$

In [2]:
import numpy as np


In [9]:
#matrix A
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [21]:
#matrix A
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
#calculate its determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)
#find inverse matrix
#1st check if determinant is 0
if det_A == 0:
  print("Matrix A is singular and has no inverse matrix\pöördmaatriks.")
else:
    inv_A = np.linalg.inv(A)
    print("inverse of A:\n\pöördmaatriks:\n", inv_A)

Determinant of A: 0.0
Matrix A is singular and has no inverse matrix\pöördmaatriks.


In [12]:
#matrix B
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 0]])

In [6]:
import numpy as np
# Define the modified matrix B
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [15, 18, 21, 24]])
# Calculate the determinant of B
det_B = np.linalg.det(B)
print("Determinant of B:", det_B)
# Find the inverse of B if the determinant is not zero
if det_B == 0:
  print("Matrix B is singular and has no inverse matrix.")
else:
  inv_B = np.linalg.inv(B)
  print("Inverse of B:\n", inv_B)

Determinant of B: 0.0
Matrix B is singular and has no inverse matrix.


... and try with differnt matrix:

$$
C=
\begin{bmatrix}
3 & 2 & -1 & 1 \\
1 & 0 & 1 & 2 \\
2 & 1 & 1 & -1 \\
1 & 1 & 1 & 0
\end{bmatrix}
$$

In [10]:
c= np.array([[3, 2, -1, 1], [1, 0, 1, 2], [2, 1, 1, -1], [1, 1, 1, 0]])

In [26]:
# Define the matrix C
C = np.array([[3, 2, -1, 1], [1, 0, 1, 2], [2, 1, 1, -1], [1, 1, 1, 0]])
# Calculate the determinant of C
det_C = np.linalg.det(C)
print("Determinant of C:", det_C)
# Find the inverse of C if the determinant is not zero
if det_C == 0:
  print("Matrix C is singular and has no inverse matrix.")
else: inv_C = np.linalg.inv(C)
print("Inverse of C:\n", inv_C)

Determinant of C: -11.000000000000002
Inverse of C:
 [[ 0.09090909  0.27272727  0.63636364 -0.81818182]
 [ 0.18181818 -0.45454545 -0.72727273  1.36363636]
 [-0.27272727  0.18181818  0.09090909  0.45454545]
 [ 0.09090909  0.27272727 -0.36363636  0.18181818]]


**<font color='#ed7d31'>SOLVING SYSTEMS OF LINEAR EQUATIONS</font>**

There are a few methods to solve systems of linear equations at a *school-level* mathematics. Although they are very effective they can require a lot of time and work, and can be especially difficult to apply to a larger number of variables. See, how you can address it with Linear Algebra.

Let's consider the following system of equations:
$$
\begin{cases}
    x_1 + x_2 = 4\\
    2x_1 - x_2 = 5
\end{cases}
$$
it can be written as $Ax = y,$ where
$$
x=\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix},
y=\begin{bmatrix}
    y_1 \\
    y_2
\end{bmatrix}=
\begin{bmatrix}
    4 \\
    5
\end{bmatrix},
$$and
$$
A=\begin{bmatrix}
1 & 1\\
2 & -1
\end{bmatrix}.
$$
If an inverse matrix $A^{-1}$ exists, you can easily solve the equation by multiplying both sides by it from the left side:
$$
Ax=y \\
x=Ix=A^{-1} Ax=A^{-1} y
$$


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.26</font>**

Solve the system of equations mentioned above.

*Correct answer: $$x = (x_1, x_2) = (3, 1).$$*

*Hint: There are functioned defined within NumPy package for both of these tasks; matrix inverse & mathematical multiplication of two matrices.*

In [23]:
# Define the matrix A and vector y
A = np.array([[1, 1], [2, -1]])
y = np.array([4, 5])
# Calculate the inverse of A
A_inv = np.linalg.inv(A)
# Solve for x
x = np.dot(A_inv, y)
print("Solution:", x)

Solution: [3. 1.]


The systems below were copied from: [Lumen: College Algebra](https://courses.lumenlearning.com/wmopen-collegealgebra/chapter/introduction-systems-of-linear-equations-three-variables/).

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.27</font>**

What is the solution to the system of equations below?
\begin{cases}
    x_1 - 2x_2+3x_3 = 9\\
    -x_1 +3x_2- x_3 = -6\\
    2x_1-5x_2+5x_3=17
\end{cases}

*Correct answer: $$x = (x_1, x_2, x_3) = (1, -1, 2).$$*

In [24]:
# Define the matrix A and vector y
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
y = np.array([9, -6, 17])
# Calculate the inverse of A
A_inv = np.linalg.inv(A)
# Solve for x
x = np.dot(A_inv, y)
print("Solution:", x)

Solution: [ 1. -1.  2.]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.28</font>**

Solve the system of equations in three variables:
\begin{cases}
    2x_1 + x_2 - 2x_3 = -1\\
    3x_1 - 3x_2 - x_3 = 5\\
    x_1 - 2x_2 + 3x_3 = 6
\end{cases}

*Correct answer: $$x = (x_1, x_2, x_3) = (1, -1, 1).$$*

In [19]:
# Define the matrix A and vector B
A = np.array([[2, 1, -2], [3, -3, -1], [1, -2, 3]])
B = np.array([-1, 5, 6])
# Calculate the inverse of A
A_inv = np.linalg.inv(A)
# Solve for X
X = np.dot(A_inv, B)
print("Solution:", X)

Solution: [ 1. -1.  1.]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.29</font>**

Determine whether the triple $x = (x_1, x_2, x_3) = (3, -2, 1)$ is a solution to the system:

\begin{cases}
    x_1 + x_2 + x_3 = 2\\
    6x_1 - 4x_2 + 5x_3 = 31\\
    5x_1 + 2x_2 + 2x_3 = 13.
\end{cases}

*Correct answer: yes, it is.*

In [18]:
# Define the values of triple x
x1, x2, x3 = 3, -2, 1
# Define the system of equations
eq1 = x1 + x2 + x3
eq2 = 6*x1 - 4*x2 + 5*x3
eq3 = 5*x1 + 2*x2 + 2*x3
# Check if the equations correct
is_solution = (eq1 == 2) and (eq2 == 31) and (eq3 == 13)
print("Is (3, -2, 1) a solution to the system of equations?", is_solution)

Is (3, -2, 1) a solution to the system of equations? True


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.30</font>**

Check whether the system solution exists:

\begin{cases}
    x_1 - 3x_2 + x_3 = 4\\
    -x_1 + 2x_2 - 5x_3 = 3\\
    5x_1 - 13x_2 + 13x_3 = 8.
\end{cases}

*Correct answer: no, it does not.*

*Hint: matrix is not full-rank, i.e $rank(A) = 2 \neq 3.$*

In [17]:
# Define the matrix A
A = np.array([[1, -3, 1], [-1, 2, -5], [5, -13, 13]])
# Calculate the rank of A
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)
# Check if the rank of A is equal to the number of variables
num_variables = A.shape[1]
has_solution = (rank_A == num_variables)
print("Does the system solution exists?", has_solution)


Rank of A: 2
Does the system solution exists? False


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.31</font>** (optional)

Find eigenvalues and eigenvectors associated with them for the following matrices:
* $
A_1=\begin{bmatrix}
-5 & 2\\
-7 & 4
\end{bmatrix}
$

* $
A_2=\begin{bmatrix}
1 & 0\\
0 & -3
\end{bmatrix}
$

* $
A_3=\begin{bmatrix}
5 & -10 & -5\\
2 & 14 & 2\\
-4 & -8 & 6
\end{bmatrix}
$

* $
A_4=\begin{bmatrix}
1 & -1 & 2\\
1 & 0 & -1\\
1 & 1 & 2
\end{bmatrix}
$

Solutions can be complex numbers, $z\in\mathbb{C}$, as for $A_4$.

In [16]:
# Define the matrices
A1 = np.array([[-5, -7], [2, 4]])
A2 = np.array([[1, 0], [0, -3]])
A3 = np.array([[5, 2, -4], [-10, 14, -8], [-5, 2, 6]])
A4 = np.array([[1, 1, 1], [-1, 0, 1], [2, -1, 2]])
# Calculate eigenvalues and eigenvectors
eigvals_A1, eigvecs_A1 = np.linalg.eig(A1)
eigvals_A2, eigvecs_A2 = np.linalg.eig(A2)
eigvals_A3, eigvecs_A3 = np.linalg.eig(A3)
eigvals_A4, eigvecs_A4 = np.linalg.eig(A4)
# Print the results print("Eigenvalues and eigenvectors for A1:")
print("Eigenvalues:", eigvals_A1)
print("Eigenvectors:\n", eigvecs_A1)
print("\nEigenvalues and eigenvectors for A2:")
print("Eigenvalues:", eigvals_A2)
print("Eigenvectors:\n", eigvecs_A2)
print("\nEigenvalues and eigenvectors for A3:")
print("Eigenvalues:", eigvals_A3)
print("Eigenvectors:\n", eigvecs_A3)
print("\nEigenvalues and eigenvectors for A4:")
print("Eigenvalues:", eigvals_A4)
print("Eigenvectors:\n", eigvecs_A4)

Eigenvalues: [-3.  2.]
Eigenvectors:
 [[-0.96152395  0.70710678]
 [ 0.27472113 -0.70710678]]

Eigenvalues and eigenvectors for A2:
Eigenvalues: [ 1. -3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]

Eigenvalues and eigenvectors for A3:
Eigenvalues: [ 5. 10. 10.]
Eigenvectors:
 [[ 0.40824829  0.0872712   0.65834173]
 [ 0.81649658  0.93036596  0.18826276]
 [ 0.40824829  0.35609398 -0.72879578]]

Eigenvalues and eigenvectors for A4:
Eigenvalues: [ 3.00000000e+00+0.j         -1.11022302e-16+1.41421356j
 -1.11022302e-16-1.41421356j]
Eigenvectors:
 [[ 4.92365964e-01+0.j   1.21295144e-16-0.5j  1.21295144e-16+0.5j]
 [ 1.23091491e-01+0.j   7.07106781e-01+0.j   7.07106781e-01-0.j ]
 [ 8.61640437e-01+0.j  -1.43583824e-17+0.5j -1.43583824e-17-0.5j]]


<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Appendix: random numbers generators

1. Randomly generated number(s) from normal (Gauss) distribution.
```python
np.random.normal()
np.random.normal(size=6)
```
1. Randomly selected numbers from the uniform system.
```python
np.random.uniform(size=6)
```
1. Randomly selected number from a specific range.
```python
np.random.randint(3, 30, size=6)
```
1. Randomly selected floating-point number
```python
np.random.random()
```